[package]
name = "linka-tui"
version.workspace = true
edition.workspace = true
description = "Terminal user interface for Linka"

[lib]
name = "linka_tui"
path = "src/lib.rs"

[[bin]]
name = "linka-tui"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["env"] }
crossterm.workspace = true
linka.workspace = true
ratatui.workspace = true
