//! The `genta` command-line tool: utilities over the coding-agent library.
//!
//! The first command, `render`, turns a recorded session log — the
//! newline-delimited wire events of a codex or Claude Code run, as captured
//! verbatim by hosts like Styra and Orka — into a readable text transcript
//! through the same decoders a live session uses.

use anyhow::{Context, Result};
use clap::{Parser, Subcommand, ValueEnum};
use genta::event::Protocol;
use genta::session::{self, ConversionOptions, SessionFormat};
use std::io::Read;
use std::path::PathBuf;

#[derive(Parser)]
#[command(name = "genta", about = "Coding-agent session tooling", version)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Render a recorded session log as a text transcript.
    Render {
        /// The log file: one wire event per line, exactly as the agent
        /// emitted them. `-` reads from stdin.
        path: PathBuf,
        /// The wire protocol the log was recorded in.
        #[arg(long, value_enum, default_value_t = Wire::Codex)]
        protocol: Wire,
        /// Also show events with no rendered view (control traffic, unknown
        /// envelopes) instead of skipping them.
        #[arg(long)]
        all: bool,
    },
    /// Convert a persisted native Claude Code or Codex CLI session.
    Convert {
        /// Source JSONL session file. `-` reads from stdin.
        input: PathBuf,
        /// Destination JSONL session file. `-` writes to stdout.
        output: PathBuf,
        #[arg(long, value_enum)]
        from: SessionWire,
        #[arg(long, value_enum)]
        to: SessionWire,
        /// Set the destination session id (a new UUID is generated by default).
        #[arg(long)]
        session_id: Option<String>,
        /// Override the destination working directory.
        #[arg(long)]
        cwd: Option<String>,
    },
}

/// Command-line names for the supported wire protocols.
#[derive(Clone, Copy, Debug, ValueEnum)]
enum Wire {
    /// `codex exec --json` output.
    Codex,
    /// `codex app-server` JSON-RPC traffic.
    CodexAppServer,
    /// Claude Code `--output-format stream-json` output.
    Claude,
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum SessionWire {
    Codex,
    Claude,
}

impl From<SessionWire> for SessionFormat {
    fn from(value: SessionWire) -> Self {
        match value {
            SessionWire::Codex => Self::Codex,
            SessionWire::Claude => Self::Claude,
        }
    }
}

impl From<Wire> for Protocol {
    fn from(wire: Wire) -> Protocol {
        match wire {
            Wire::Codex => Protocol::CodexJsonl,
            Wire::CodexAppServer => Protocol::CodexAppServer,
            Wire::Claude => Protocol::ClaudeJsonl,
        }
    }
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Command::Render {
            path,
            protocol,
            all,
        } => {
            let log = read_input(&path)?;
            // The CLI has no notion of "minor" lifecycle events to hide, unlike
            // Styra's TUI toggle; always show them here.
            print!(
                "{}",
                genta::render::render(&log, protocol.into(), all, true)
            );
        }
        Command::Convert {
            input,
            output,
            from,
            to,
            session_id,
            cwd,
        } => {
            let converted = session::convert(
                &read_input(&input)?,
                from.into(),
                to.into(),
                &ConversionOptions {
                    id: session_id,
                    cwd,
                    ..Default::default()
                },
            )?;
            if output.as_os_str() == "-" {
                print!("{converted}");
            } else {
                std::fs::write(&output, converted).with_context(|| {
                    format!("writing the converted session {}", output.display())
                })?;
            }
        }
    }
    Ok(())
}

fn read_input(path: &PathBuf) -> Result<String> {
    if path.as_os_str() == "-" {
        let mut log = String::new();
        std::io::stdin()
            .read_to_string(&mut log)
            .context("reading the session log from stdin")?;
        Ok(log)
    } else {
        std::fs::read_to_string(path)
            .with_context(|| format!("reading the session log {}", path.display()))
    }
}
