[package]
name = "driva"
version.workspace = true
edition.workspace = true
description = "A deny-by-default isolated command runner"

[lib]
name = "driva"
path = "src/lib.rs"

[[bin]]
name = "driva"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
toml.workspace = true
