//! User-visible commands offered by the terminal client.
//!
//! This is the command catalog: it names what an operator can ask Styra to
//! do and supplies the text shown in the keyboard reference. The actual key
//! assignments live separately in [`crate::keybindings`].

/// A command the operator can invoke through a key binding.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Action {
    Help,
    GlobalFocusMessage,
    GlobalLeaveMessage,
    GlobalBack,
    GlobalQuit,
    GlobalInterrupt,
    GlobalStop,
    GlobalBranch,
    GlobalNextLive,
    GlobalNextWorking,
    GlobalNewSession,
    GlobalLauncher,
    GlobalShell,
    GlobalDirectory,
    GlobalInteractions,
    GlobalOverview,
    GlobalSessions,
    GlobalWorkspaces,
    GlobalWorktrees,
    GlobalSessionWorktree,
    GlobalTags,
    GlobalRaw,
    GlobalLog,
    GlobalTranscript,
    GlobalDetails,
    GlobalJumpBack,
    GlobalAutoCommit,
    GlobalEntryLog,
    GlobalEntryLogFocus,
    GlobalQuota,
    GlobalFiles,
    GlobalAnswer,
    GlobalPreview,
    GlobalCopyConversation,
    EventsPreviewScrollDown,
    EventsPreviewScrollUp,
    EventsScrollDown,
    EventsScrollUp,
    EventsNextEntry,
    EventsPrevEntry,
    EventsNextLine,
    EventsPrevLine,
    EventsFirst,
    EventsLast,
    EventsFollowBranch,
    EventsToggleExpand,
    EventsExpandOnly,
    EventsExpandAll,
    EventsCollapseAll,
    EventsMinor,
    EventsPreviewPanel,
    EventsAllEvents,
    EventsPreviewTarget,
    EventsComplete,
    EventsAbandon,
    EventsLinkDestinations,
    EventsSearch,
    EventsPageDown,
    EventsPageUp,
    EventsLinks,
    EventsLinkMenu,
    EventsCopy,
    ReadingDown,
    ReadingUp,
    ReadingFirst,
    ReadingLast,
    ReadingLinks,
    ReadingAllEvents,
    ReadingRetry,
    ReadingPageDown,
    ReadingPageUp,
    ReadingProviderRaw,
    ReadingCopy,
    PreviewScrollDown,
    PreviewScrollUp,
    PreviewNextEntry,
    PreviewPrevEntry,
    PreviewPageDown,
    PreviewPageUp,
    PreviewFirst,
    PreviewLast,
    PreviewTarget,
    PreviewLinks,
    PreviewLinkDestinations,
    PreviewCopy,
    DrivaTab,
    DrivaScope,
    DrivaNextMount,
    DrivaPrevMount,
    DrivaNetwork,
    DrivaAccess,
    DrivaTemplates,
    DrivaAddMount,
    DrivaGitCheckout,
    DrivaRemoveMount,
    DrivaIgnoreWorkspace,
    DrivaPromote,
    DrivaSaveDefault,
    DrivaPageDown,
    DrivaPageUp,
    FilesNext,
    FilesPrev,
    FilesNextEntry,
    FilesPrevEntry,
    FilesFirst,
    FilesLast,
    FilesEdit,
    FilesPreview,
    FilesScope,
    FilesCopy,
    AnswerNext,
    AnswerPrev,
    AnswerFirst,
    AnswerLast,
    AnswerEdit,
    AnswerCopy,
    AnswerAsText,
    AnswerAsLines,
    AnswerAsFiles,
    AnswerAsJson,
    AnswerReread,
    EditorRecord,
    EditorRecordFinish,
    EditorRecordCancel,
    EditorRecordLouder,
    EditorRecordQuieter,
    EditorContract,
    EditorSend,
    EditorSendInBranch,
    EditorChangeDirectory,
    EditorNewline,
    EditorHistoryOlder,
    EditorHistoryNewer,
    EditorDeleteWord,
    EditorLauncher,
    EditorInsertPath,
    EditorMountReadable,
    EditorMountWritable,
    EditorMountNeither,
    InteractionsNext,
    InteractionsPrev,
    InteractionsNextWorkspace,
    InteractionsPrevWorkspace,
    InteractionsNextWorking,
    InteractionsPrevWorking,
    InteractionsNextIdle,
    InteractionsScope,
    InteractionsCompleted,
    InteractionsComplete,
    InteractionsAbandon,
    InteractionsTags,
    InteractionsStop,
    InteractionsDelete,
    InteractionsFilter,
    InteractionsClose,
    OverviewLeft,
    OverviewRight,
    OverviewDown,
    OverviewUp,
    OverviewNext,
    OverviewPrev,
    OverviewFirst,
    OverviewLast,
    OverviewOpen,
    OverviewMessage,
    OverviewClose,
    BranchNext,
    BranchPrev,
    BranchConfirm,
    BranchCancel,
    LinkMenuNext,
    LinkMenuPrev,
    LinkMenuConfirm,
    LinkMenuCancel,
    TagsFilter,
    TagsNext,
    TagsPrev,
    TagsPageDown,
    TagsPageUp,
    TagsDeleteWord,
    TagsToggle,
    TagsNew,
    TagsSave,
    TagsCancel,
    SessionsHelp,
    SessionsNext,
    SessionsPrev,
    SessionsNextRoot,
    SessionsPrevRoot,
    SessionsFirst,
    SessionsLast,
    SessionsOpen,
    SessionsNew,
    SessionsCompleted,
    SessionsComplete,
    SessionsAbandon,
    SessionsFilter,
    SessionsSort,
    SessionsOlder,
    SessionsRename,
    SessionsConvert,
    SessionsCancel,
    WorkspacesHelp,
    WorkspacesNext,
    WorkspacesPrev,
    WorkspacesOpen,
    WorkspacesNew,
    WorkspacesCreate,
    WorkspacesRename,
    WorkspacesDirectory,
    WorkspacesFilter,
    WorkspacesDeleteWord,
    WorkspacesCancel,
    WorktreesFilter,
    WorktreesHelp,
    WorktreesNext,
    WorktreesPrev,
    WorktreesPageDown,
    WorktreesPageUp,
    WorktreesDeleteWord,
    WorktreesScope,
    WorktreesOpen,
    WorktreesCancel,
    LauncherHelp,
    LauncherNext,
    LauncherPrev,
    LauncherFilter,
    LauncherPageDown,
    LauncherPageUp,
    LauncherDeleteWord,
    LauncherSelect,
    LauncherDefault,
    LauncherCancel,
    TemplatesHelp,
    TemplatesNext,
    TemplatesPrev,
    TemplatesToggle,
    TemplatesApply,
    TemplatesCancel,
    EventsFoldPrefix,
    CloseReference,
    ReferenceDown,
    ReferenceUp,
    ReferencePageDown,
    ReferencePageUp,
    ReferenceTop,
}

impl Action {
    /// Human-readable command text used by the keyboard reference.
    pub(crate) const fn description(self) -> &'static str {
        match self {
            Self::Help => "show/close the reference for this window",
            Self::GlobalFocusMessage => "focus the message box",
            Self::GlobalLeaveMessage => "return to the list",
            Self::GlobalBack => "return to the event list",
            Self::GlobalQuit => "quit",
            Self::GlobalInterrupt => "interrupt the active turn",
            Self::GlobalStop => "stop the interaction",
            Self::GlobalBranch => "branch from history through, or only, the selected entry",
            Self::GlobalNextLive => "step to the next interaction that is still running",
            Self::GlobalNextWorking => "step to the next interaction actively working",
            Self::GlobalNewSession => "new session where this one works",
            Self::GlobalLauncher => "choose agent, model and effort for an idle agent turn",
            Self::GlobalShell => "open session shell in a new terminal",
            Self::GlobalDirectory => "open a terminal in the interaction's working directory",
            Self::GlobalInteractions => "live interactions",
            Self::GlobalOverview => "overview: every running and idle interaction as a grid",
            Self::GlobalSessions => "stored sessions",
            Self::GlobalWorkspaces => "Workspaces",
            Self::GlobalWorktrees => "worktrees and the sessions in each",
            Self::GlobalSessionWorktree => "create and associate a Git branch and workspace",
            Self::GlobalTags => "edit the current interaction's tags",
            Self::GlobalRaw => "raw view; press again for events",
            Self::GlobalLog => "log view; press again for events",
            Self::GlobalTranscript => "transcript view; press again for events",
            Self::GlobalDetails => "details view; press again for events",
            Self::GlobalJumpBack => "go back to the interaction viewed before following a link",
            Self::GlobalAutoCommit => "commit each turn's work when it goes idle (on/off)",
            Self::GlobalEntryLog => "toggle the entry log below the event list",
            Self::GlobalEntryLogFocus => "move between the event list and the open entry log",
            Self::GlobalQuota => "plan quota readings, refreshed from the server",
            Self::GlobalFiles => "files mentioned by the focused entry",
            Self::GlobalAnswer => "the last turn's typed answer",
            Self::GlobalPreview => "toggle full-screen preview",
            Self::GlobalCopyConversation => "copy the whole conversation (any view)",
            Self::EventsPreviewScrollDown => "scroll the preview 10 lines down",
            Self::EventsPreviewScrollUp => "scroll the preview 10 lines up",
            Self::EventsScrollDown => {
                "scroll the interaction 10 lines down without moving the selection"
            }
            Self::EventsScrollUp => {
                "scroll the interaction 10 lines up without moving the selection"
            }
            Self::EventsNextEntry => "next entry",
            Self::EventsPrevEntry => "previous entry",
            Self::EventsNextLine => "next line, or next link while links are highlighted",
            Self::EventsPrevLine => "previous line, or previous link",
            Self::EventsFirst => "first entry",
            Self::EventsLast => "last entry",
            Self::EventsFollowBranch => "follow the linked Session",
            Self::EventsToggleExpand => "toggle selected entry",
            Self::EventsExpandOnly => "expand only selected",
            Self::EventsExpandAll => "expand all",
            Self::EventsCollapseAll => "collapse all",
            Self::EventsMinor => "toggle minor events",
            Self::EventsPreviewPanel => "toggle preview panel",
            Self::EventsAllEvents => "toggle all events (conversation only by default)",
            Self::EventsPreviewTarget => "preview the newest command",
            Self::EventsComplete => "mark this interaction completed and stop it",
            Self::EventsAbandon => "mark this interaction abandoned and stop it",
            Self::EventsLinkDestinations => "toggle link destinations",
            Self::EventsSearch => {
                "search: mark words matching a term of 3+ characters (Esc clears)"
            }
            Self::EventsPageDown => "scroll the preview half a page, or the entry log, down",
            Self::EventsPageUp => "scroll the preview half a page, or the entry log, up",
            Self::EventsLinks => {
                "highlight conversation links (j/k moves, Enter opens, Space offers actions, Esc exits)"
            }
            Self::EventsLinkMenu => "actions on the highlighted link",
            Self::EventsCopy => "copy selected entry to clipboard",
            Self::ReadingDown => "move or scroll down",
            Self::ReadingUp => "move or scroll up",
            Self::ReadingFirst => "first line, or top",
            Self::ReadingLast => "last line, or bottom",
            Self::ReadingLinks => {
                "highlight conversation links (j/k moves, Enter opens, Esc exits)"
            }
            Self::ReadingAllEvents => "toggle all events (conversation only by default)",
            Self::ReadingRetry => {
                "after a rate limit, ask this session again once the window resets"
            }
            Self::ReadingPageDown => "scroll the raw-line preview down",
            Self::ReadingPageUp => "scroll the raw-line preview up",
            Self::ReadingProviderRaw => "switch Styra wire capture / provider-native session JSONL",
            Self::ReadingCopy => "copy selected line to clipboard",
            Self::PreviewScrollDown => "scroll 10 lines down, or step to the next link",
            Self::PreviewScrollUp => "scroll 10 lines up, or step to the previous link",
            Self::PreviewNextEntry => "next entry",
            Self::PreviewPrevEntry => "previous entry",
            Self::PreviewPageDown => "scroll half a page down",
            Self::PreviewPageUp => "scroll half a page up",
            Self::PreviewFirst => "first entry",
            Self::PreviewLast => "last entry",
            Self::PreviewTarget => "preview the newest command",
            Self::PreviewLinks => "highlight conversation links",
            Self::PreviewLinkDestinations => "toggle link destinations",
            Self::PreviewCopy => "copy the previewed entry to clipboard",
            Self::DrivaTab => "switch between Details and Sandbox",
            Self::DrivaScope => "edit the Workspace's policy / this interaction's",
            Self::DrivaNextMount => "next mount",
            Self::DrivaPrevMount => "previous mount",
            Self::DrivaNetwork => "permit/forbid agent networking, in the focused layer",
            Self::DrivaAccess => "mount the workspace read-write/read-only, in the focused layer",
            Self::DrivaTemplates => "choose Driva templates",
            Self::DrivaAddMount => "add a mount",
            Self::DrivaGitCheckout => "set this Workspace's Git checkout",
            Self::DrivaRemoveMount => "remove selected mount",
            Self::DrivaIgnoreWorkspace => "this interaction adds to / ignores the Workspace policy",
            Self::DrivaPromote => "move this interaction's policy up into the Workspace's",
            Self::DrivaSaveDefault => "save this interaction's policy for new clients",
            Self::DrivaPageDown => "scroll the current Details or Sandbox page down",
            Self::DrivaPageUp => "scroll the current Details or Sandbox page up",
            Self::FilesNext => "next file",
            Self::FilesPrev => "previous file",
            Self::FilesNextEntry => "next interaction-log entry",
            Self::FilesPrevEntry => "previous interaction-log entry",
            Self::FilesFirst => "first file",
            Self::FilesLast => "last file",
            Self::FilesEdit => "open selected file in editor",
            Self::FilesPreview => "toggle interaction preview",
            Self::FilesScope => "focused-entry / all-session files",
            Self::FilesCopy => "copy the path",
            Self::AnswerNext => "next item",
            Self::AnswerPrev => "previous item",
            Self::AnswerFirst => "first item",
            Self::AnswerLast => "last item",
            Self::AnswerEdit => "open location in editor",
            Self::AnswerCopy => "copy",
            Self::AnswerAsText => "re-read as text",
            Self::AnswerAsLines => "re-read as lines",
            Self::AnswerAsFiles => "re-read as files",
            Self::AnswerAsJson => "re-read as json",
            Self::AnswerReread => "re-read as the turn asked",
            Self::EditorRecord => "record from the microphone; the box becomes a level meter",
            Self::EditorRecordFinish => "transcribe into the message",
            Self::EditorRecordCancel => "discard the recording",
            Self::EditorRecordLouder => "boost a quiet input",
            Self::EditorRecordQuieter => "take a loud input down",
            Self::EditorContract => "ask this message's reply for a shape (text/lines/files/json)",
            Self::EditorSend => "send message",
            Self::EditorSendInBranch => "send in a new Git branch and workspace",
            Self::EditorChangeDirectory => "change the live Codex interaction directory",
            Self::EditorNewline => "insert newline",
            Self::EditorHistoryOlder => "older message history",
            Self::EditorHistoryNewer => "newer message history",
            Self::EditorDeleteWord => "delete previous word",
            Self::EditorLauncher => "choose model before first message or idle agent turn",
            Self::EditorInsertPath => "insert a file path (Tab completes, Enter inserts)",
            Self::EditorMountReadable => "mount it readable",
            Self::EditorMountWritable => "mount it writable",
            Self::EditorMountNeither => "insert it with no mount",
            Self::InteractionsNext => {
                "move the cursor down; the rested-on interaction becomes current"
            }
            Self::InteractionsPrev => "move the cursor up",
            Self::InteractionsNextWorkspace => "first interaction of the next Workspace, in All",
            Self::InteractionsPrevWorkspace => {
                "first interaction of the previous Workspace, in All"
            }
            Self::InteractionsNextWorking => {
                "next interaction actively working, skipping idle ones"
            }
            Self::InteractionsPrevWorking => {
                "previous interaction actively working, skipping idle ones"
            }
            Self::InteractionsNextIdle => "next interaction that went idle unseen",
            Self::InteractionsScope => "current Workspace / all Workspaces",
            Self::InteractionsCompleted => "show/hide completed",
            Self::InteractionsComplete => "mark selected completed and stop it",
            Self::InteractionsAbandon => "mark selected abandoned and stop it",
            Self::InteractionsTags => "edit the selected interaction's tags",
            Self::InteractionsStop => "stop the selected interaction",
            Self::InteractionsDelete => "delete it once stopped",
            Self::InteractionsFilter => {
                "filter by name, tag, branch, provider or Workspace (Enter opens the selection, Esc clears it)"
            }
            Self::InteractionsClose => "clear the filter, or close the list",
            Self::OverviewLeft => "previous tile",
            Self::OverviewRight => "next tile",
            Self::OverviewDown => "tile below",
            Self::OverviewUp => "tile above",
            Self::OverviewNext => "next tile, wrapping",
            Self::OverviewPrev => "previous tile, wrapping",
            Self::OverviewFirst => "first tile",
            Self::OverviewLast => "last tile",
            Self::OverviewOpen => "open the selected interaction",
            Self::OverviewMessage => "message the selected interaction",
            Self::OverviewClose => "return to the event list",
            Self::BranchNext => "entire interaction through this entry",
            Self::BranchPrev => "only this entry",
            Self::BranchConfirm => "branch, and open the result",
            Self::BranchCancel => "cancel",
            Self::LinkMenuNext => "next action",
            Self::LinkMenuPrev => "previous action",
            Self::LinkMenuConfirm => "take the selected action",
            Self::LinkMenuCancel => "cancel",
            Self::TagsFilter => "narrow the list to what is typed",
            Self::TagsNext => "move selection down",
            Self::TagsPrev => "move selection up",
            Self::TagsPageDown => "move selection a page down",
            Self::TagsPageUp => "move selection a page up",
            Self::TagsDeleteWord => "delete the last word of the filter",
            Self::TagsToggle => "toggle the selected tag",
            Self::TagsNew => "add a new tag, starting from the filter (Enter adds and saves)",
            Self::TagsSave => "save",
            Self::TagsCancel => "clear the filter, or cancel",
            Self::SessionsHelp => "show/close this reference",
            Self::SessionsNext => "move selection down",
            Self::SessionsPrev => "move selection up",
            Self::SessionsNextRoot => "next root conversation, skipping its branches",
            Self::SessionsPrevRoot => "previous root conversation",
            Self::SessionsFirst => "first session",
            Self::SessionsLast => "last session",
            Self::SessionsOpen => "open the selected session",
            Self::SessionsNew => "start a new session in this Workspace",
            Self::SessionsCompleted => "show/hide completed",
            Self::SessionsComplete => "mark selected completed or not",
            Self::SessionsAbandon => "mark selected abandoned or not",
            Self::SessionsFilter => "filter by name or first prompt (Esc clears)",
            Self::SessionsSort => "sort by last activity / by creation",
            Self::SessionsOlder => "show/hide history older than a week",
            Self::SessionsRename => "rename the selected session",
            Self::SessionsConvert => "convert the selected session to the other provider",
            Self::SessionsCancel => "cancel",
            Self::WorkspacesHelp => "show/close this reference",
            Self::WorkspacesNext => "move selection down",
            Self::WorkspacesPrev => "move selection up",
            Self::WorkspacesOpen => "open the selected Workspace",
            Self::WorkspacesNew => "start a new interaction in the selected Workspace",
            Self::WorkspacesCreate => "create a Workspace for the current directory",
            Self::WorkspacesRename => "rename the selected Workspace",
            Self::WorkspacesDirectory => "change the selected Workspace's directory",
            Self::WorkspacesFilter => {
                "narrow the list by name or path to what is typed (Esc clears)"
            }
            Self::WorkspacesDeleteWord => "delete the last word of the filter",
            Self::WorkspacesCancel => "cancel",
            Self::WorktreesFilter => {
                "narrow the list by checkout, branch or session to what is typed (Esc clears)"
            }
            Self::WorktreesHelp => "show/close this reference",
            Self::WorktreesNext => "move selection down",
            Self::WorktreesPrev => "move selection up",
            Self::WorktreesPageDown => "page down",
            Self::WorktreesPageUp => "page up",
            Self::WorktreesDeleteWord => "delete the last word of the filter",
            Self::WorktreesScope => "this Workspace / every Workspace",
            Self::WorktreesOpen => "open the selected session",
            Self::WorktreesCancel => "cancel",
            Self::LauncherHelp => "show/close this reference",
            Self::LauncherNext => "move down the matching rows",
            Self::LauncherPrev => "move up the matching rows",
            Self::LauncherFilter => "narrow the list to what is typed",
            Self::LauncherPageDown => "move a page down the matching rows",
            Self::LauncherPageUp => "move a page up the matching rows",
            Self::LauncherDeleteWord => "delete the last word of the query",
            Self::LauncherSelect => "launch on the selected row",
            Self::LauncherDefault => "select and save launch default",
            Self::LauncherCancel => "cancel",
            Self::TemplatesHelp => "show/close this reference",
            Self::TemplatesNext => "move selection down",
            Self::TemplatesPrev => "move selection up",
            Self::TemplatesToggle => "add/remove the selected template",
            Self::TemplatesApply => "apply; templates layer in the order chosen",
            Self::TemplatesCancel => "cancel",
            Self::EventsFoldPrefix => "fold prefix: z R expands all, z M collapses all",
            Self::CloseReference => "close the reference",
            Self::ReferenceDown => "scroll down",
            Self::ReferenceUp => "scroll up",
            Self::ReferencePageDown => "page down",
            Self::ReferencePageUp => "page up",
            Self::ReferenceTop => "back to the top",
        }
    }
}
